version: '3.8'

services:
  web:
    build: ..
    command: gunicorn -b 0.0.0.0:8000 run:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# # 如果使用 Nginx 作为反向代理
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../app/static:/app/app/static
#      - /etc/letsencrypt:/etc/letsencrypt  # 如果使用 SSL
#    depends_on:
#      - web

volumes:
  db_data: