"""Add date_joined to User model

Revision ID: ff6d7a235d03
Revises: 85ac2ca3d2a6
Create Date: 2024-09-19 08:48:03.930898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6d7a235d03'
down_revision = '85ac2ca3d2a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
